// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpexkqlibqmtkvehalyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZXhrcWxpYnFtdGt2ZWhhbHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDQ4ODIsImV4cCI6MjA2NTU4MDg4Mn0.AvyWJPBNrKDrUOKeg9d8Cvxc4Xc5cVNYP-YGS8EVvKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);